<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Cryptography History Report</title>

    <style>
        body{
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color:#111827;
        }

        .header{
            text-align:center;
            border-bottom:3px solid #2563eb;
            padding-bottom:15px;
            margin-bottom:25px;
        }

        .header h1{
            margin:0;
            color:#1e3a8a;
            font-size:24px;
        }

        .header p{
            margin:5px 0 0;
            color:#6b7280;
        }

        .summary{
            margin-bottom:20px;
            padding:12px;
            background:#eff6ff;
            border-left:5px solid #2563eb;
        }

        table{
            width:100%;
            border-collapse:collapse;
        }

        th{
            background:#1e3a8a;
            color:white;
            padding:10px;
            text-align:left;
            font-size:11px;
        }

        td{
            border:1px solid #d1d5db;
            padding:8px;
            vertical-align:top;
            word-break:break-word;
        }

        tr:nth-child(even){
            background:#f9fafb;
        }

        .badge{
            display:inline-block;
            padding:4px 8px;
            border-radius:6px;
            color:white;
            font-size:10px;
            font-weight:bold;
        }

        .encrypt{
            background:#16a34a;
        }

        .decrypt{
            background:#dc2626;
        }

        .footer{
            margin-top:30px;
            text-align:center;
            font-size:10px;
            color:#6b7280;
            border-top:1px solid #d1d5db;
            padding-top:10px;
        }
    </style>
</head>
<body>

<div class="header">
    <h1>🔐 Cryptography History Report</h1>
    <p>Secure Cryptography System - Laravel Project</p>
</div>

<div class="summary">
    <strong>Total History:</strong> {{ $histories->count() }} data<br>
    <strong>Generated At:</strong> {{ now()->format('d M Y H:i') }}
</div>

<table>
    <thead>
        <tr>
            <th width="5%">No</th>
            <th width="12%">Action</th>
            <th width="15%">Algorithm</th>
            <th width="25%">Input</th>
            <th width="30%">Result</th>
            <th width="13%">Date</th>
        </tr>
    </thead>

    <tbody>
        @foreach($histories as $index => $history)
        <tr>
            <td>{{ $index + 1 }}</td>

            <td>
                @if($history->action == 'ENCRYPT')
                    <span class="badge encrypt">ENCRYPT</span>
                @else
                    <span class="badge decrypt">DECRYPT</span>
                @endif
            </td>

            <td>{{ $history->algorithm }}</td>

            <td>{{ $history->input_text }}</td>

            <td>{{ $history->result_text }}</td>

            <td>{{ $history->created_at->format('d M Y H:i') }}</td>
        </tr>
        @endforeach
    </tbody>
</table>

<div class="footer">
    Generated by Secure Cryptography System using Laravel
</div>

</body>
</html>